name: AutoRestart
main: cn.stevei5mc.autorestart.AutoRestartPlugin
version: "1.0.0"
author: stevei5mc
api: ["1.0.14"]

permissions:
  autorestart.admin:
    description: "插件主权限"
    default: op
  autorestart.admin.reload:
    description: "插件重载权限"
    default: op
  autorestart.admin.cancel:
    description: "取消重启任务权限"
    default: op
  autorestart.admin.restart:
    description: "手动重启权限"
    default: op
  autorestart.admin.pause:
    description: "暂停或继续运行任务的权限"
    default: op
  autorestart.admin.vote.veto:
    description: "一票否决权"
    default: op
  autorestart.admin.vote.force:
    description: "在调试模式中强制发起投票"
    default: op
  autorestart.user.vote:
    description: "投票权限"
    default: true