name: AutoRestart
main: cn.stevei5mc.autorestart.AutoRestartPlugin
version: "1.0.0-beta4"
author: stevei5mc
api: ["1.0.14"]

permissions:
  autorestart.admin:
    description: "插件主权限"
    default: op
  autorestart.admin.reload:
    description: "插件重载权限"
    default: op
  autorestart.admin.cancel:
    description: "取消重启任务权限"
    default: op
  autorestart.admin.restart:
    description: "手动重启权限"
    default: op