name: tag push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4.1.1
    - name: 安装java8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Extractor pom.xml gav info 
      id: getPomInfo
      run: |
        echo "groupId=$(mvn help:evaluate -f ${{ env.pomPath }} -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "artifactId=$(mvn help:evaluate -f ${{ env.pomPath }} -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
        echo "version=$(mvn help:evaluate -f ${{ env.pomPath }} -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: Show get pom.xml gav info
      run: |
        echo Group id: ${{ steps.getPomInfo.outputs.group-id }}
        echo Artifact id: ${{ steps.getPomInfo.outputs.artifact-id }}
        echo Version: ${{ steps.getPomInfo.outputs.version }}
    - name: 修复pom.xml错误的版本号
      if: steps.getPomInfo.outputs.version != steps.get_info.outputs.version
      run: |
        echo "::warning::pom.xml中的版本 ${{ steps.getPomInfo.outputs.version }} 与Git标签版本 ${{ steps.get_info.outputs.version }} 不匹配，请尝试修复"
        mvn versions:set -DnewVersion=${{ steps.get_info.outputs.version }}
    - name: 获取脚本资源
      uses: actions/checkout@v4.1.1
      with:
        repository: 'stevei5mc/McStartServer'
        path: ./script
    - name: 安装java8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        # server-id: jitpack
        # server-username: ${{ secrets.JITPACK_USER }}
        # server-password: ${{ secrets.JITPACK_PASS }}
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
    - name: 整理脚本资源
      run: |
        pwd
        cp ./script/server_script/Windows/*.bat staging
        cp ./script/server_script/Linux/*.sh staging
        cd ./staging
        zip -r Windows-script.zip ./*.bat
        zip -r Linux-script.zip ./*.sh
        ls -la
        cd ../
        mkdir github_artifact
        cp ./staging/*.zip github_artifact
        cp ./staging/*.jar github_artifact
        ls -la
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ steps.get_info.outputs.repository_name }}-Release-${{ steps.get_info.outputs.version }}
        path: github_artifact 
    - name: 发布新版本
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ steps.get_info.outputs.version }}
        name: ${{ steps.get_info.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: ./docs/changelogs/${{ steps.get_info.outputs.version }}.md
        artifacts: ./staging/*.*
    #这个暂时没有用
    # - name: 发布至minebbs
    #   uses: engsr6982/upload-minebbs@v1.2.0
    #   with: 
    #     minebbs_token: ${{ secrets.MINEBBS_TOKEN }}
    #     resource_id: "12345"
    #     upload_file: ./github_artifact/*.*
    #     update_title: ${{ steps.get_info.outputs.VERSION }}
    #     update_version: ${{ steps.get_info.outputs.VERSION }}