name: tag push
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 获取信息
      id: get_info
      run: |
        echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        echo "repository_name=${GITHUB_REPOSITORY/${{ github.repository_owner }}\//}" >> $GITHUB_OUTPUT
    - name: 拉取代码
      uses: actions/checkout@v4.1.6
      with:
        submodules: true
    - name: 安装java8
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: 构建
      run: |
        mvn -B package --file pom.xml
        mkdir staging
        cp target/*.jar staging
    - name: 准备资源
      run: |
        pwd
        cp ./script/server_script/Windows/*.bat staging
        cp ./script/server_script/Linux/*.sh staging
        cd ./staging
        zip -r Windows-script.zip ./*.bat
        zip -r Linux-script.zip ./*.sh
        ls -ls
        cd ../
        mkdir github_artifact
        cp ./staging/*.zip github_artifact
        cp ./staging/*.jar github_artifact
        ls -ls
    - name: 收集构建文件
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ steps.get_info.outputs.repository_name }}-Release-${{ steps.get_info.outputs.VERSION }}
        path: github_artifact 
    - name: 发布新版本
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ steps.get_info.outputs.VERSION }}
        name: ${{ steps.get_info.outputs.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        bodyFile: ./docs/changelogs/${{ steps.get_info.outputs.VERSION }}.md
        artifacts: ./staging/*.*
    #这个暂时没有用
    # - name: 发布至minebbs
    #   uses: engsr6982/upload-minebbs@v1.2.0
    #   with: 
    #     minebbs_token: ${{ secrets.MINEBBS_TOKEN }}
    #     resource_id: "12345"
    #     upload_file: ./github_artifact/*.*
    #     update_title: ${{ steps.get_info.outputs.VERSION }}
    #     update_version: ${{ steps.get_info.outputs.VERSION }}